### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by krystian987** [OnlyNoobDied/GadgetsMenu#1007]
**Describe the bug**
Randomly an error appears in the console

**Expected behavior**
No error

**Further Information:**
 - Server Version: Purpur 1.19.4
 - GadgetsMenu Version: 5.22.2

[Craft Scheduler Thread - 1050 - GadgetsMenu/WARN]: [GadgetsMenu] Plugin GadgetsMenu v5.22.2 generated an exception while executing task 7913450
java.lang.IllegalArgumentException: Player cannot be null.
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
	at com.yapzhenyie.GadgetsMenu.utils.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:914) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.utils.ParticleEffect.display(ParticleEffect.java:255) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.cloaks.types.CloakScanner.active(CloakScanner.java:41) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.cloaks.types.CloakScanner.onUpdate(CloakScanner.java:25) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.cloaks.types.Cloak$1.run(Cloak.java:101) ~[GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.

**Comment by krystian987** [comment]
Unfortunately, a similar error still occurs:

[Craft Scheduler Thread - 987 - GadgetsMenu/WARN]: [GadgetsMenu] Plugin GadgetsMenu v5.23.0 generated an exception while executing task 4257008
java.lang.IllegalArgumentException: Player cannot be null.
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
	at com.yapzhenyie.GadgetsMenu.utils.ParticleEffect$ParticlePacket.sendTo(ParticleEffect.java:914) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.utils.ParticleEffect.displayColor(ParticleEffect.java:410) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.cloaks.types.CloakArchangel.active(CloakArchangel.java:89) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.cloaks.types.CloakArchangel.onUpdate(CloakArchangel.java:39) ~[GadgetsMenu.jar:?]
	at com.yapzhenyie.GadgetsMenu.cosmetics.cloaks.types.Cloak$1.run(Cloak.java:101) ~[GadgetsMenu.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
