### ISSUE TITLE
Gadgets and CanBeFound: true

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#206]
I have enable vault and purchasable chest with playerpoints.
i noticed after 1 month, players still not find and gadgets under gadgets categogry,  instead other category work fine, i think is a bug....

**Comment by Maxetto** [comment]
I can confirm that Gadgets doesn't appear inside Treasure Chest's rewards.

**Comment by OnlyNoobDied** [comment]
Fixed. Sorry for my wrong minor setting.

**Comment by Maxetto** [comment]
Seems like it's not yet fixed.

Items appear inside the Chest, but in fact the never get picked.

**Comment by xion87** [comment]
for me is working player have obtained 17 gadgets item today

**Comment by Maxetto** [comment]
Ok, ok. They just have been unlucky.
I got CATapult. Fixed ;)
