### ISSUE TITLE
Parachute gadget does not launch player to air

### ISSUE THREAD

**Issue by FaberoM** [OnlyNoobDied/GadgetsMenu#776]
**Describe the bug**
The title pretty much says it all. You don't get launched and the player stays on the ground the whole time, no errors tho.

**To Reproduce**
Use parachute gadget

**Expected behavior**
A player would get launched to the air instead of being on the ground the whole time.

**Further Information (please complete the following information):**
 - Server Version: 1.15.2
 - GadgetsMenu Version: 4.5.21

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.

**Comment by FaberoM** [comment]
I can confirm this is still an issue with version 4.5.22. See the image attached bellow:

![Screenshot 2020-05-29 at 19 45 15](https://user-images.githubusercontent.com/44451855/83284549-79b96f80-a1e5-11ea-915c-ea2ce829fb57.jpg)

**Comment by OnlyNoobDied** [comment]
It might be plugin conflict. If it didn't launch player to the air, it won't spawn chickens.

**Comment by FaberoM** [comment]
Ah, I got it resolved. I had `tick-armor-stands` false in paper's config which caused the problem. :)
